apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels: 
        app: example
    spec: 
      containers:
        - name: mycontainer
          image: kubedevio/nginx-color:green
