apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-taint
  name: app-taint
spec:
  containers:
  - image: nginx
    name: app-taint
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
      kubernetes.io/hostname: knode03
  tolerations:
  - key: "dedicated"
    effect: "NoSchedule" 
status: {}
