apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    name: multi-containers
spec:
  restartPolicy: Never
  containers:

  - name: multi-containers
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  - name: busy-containers
    image: busybox:1.34
    command: [ "sleep", "1d" ]
