apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replicaset
  labels:
    app: blue-green
    name: first-replicaset
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: mycontainer
          image: kubedevio/nginx-color:blue